name: Build and Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 동일한 브랜치에 대해 실행 중인 이전 워크플로우를 취소하고 마지막 것만 실행하도록 설정
concurrency:
  group: "build-and-deploy-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 일정 시간 대기해서 여러 푸시가 연달아 일어났을 때 마지막 푸시만 반영되도록 함 (여기서는 60초)
      - name: Wait for stabilization (debounce)
        run: sleep 60

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install
        working-directory: ./source

      - name: chmod
        run: chmod +x ./quartz/bootstrap-cli.mjs
        working-directory: ./source

      - name: Ensure Quartz builds, check bundle info
        run: npx quartz build --bundleInfo
        working-directory: ./source

  deploy:
    needs: build-and-test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Quartz
        run: |
          npm install
          npx quartz build
        working-directory: ./source

      - name: Copy raw HTML folder
        run: |
          cp -r raw_html/* public/
        working-directory: ./source

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./source/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
