name: 배포

on:
  push:
    branches:
      - main
    paths:
      - 'source/content/**'  # source/content 하위에 변경이 있을 때만 실행

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 Checkout (최신 커밋만 가져오기)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 6

      # 2. source/content/ 내 변경사항이 있는지 체크 (변경사항이 없으면 스킵)
      - name: Check for changes in source/content
        id: content_check
        run: |
          if [ -z "$(git diff HEAD^ HEAD -- source/content)" ]; then
            echo "No changes in source/content."
            echo "::set-output name=changed::false"
          else
            echo "Changes detected in source/content."
            echo "::set-output name=changed::true"
          fi

      - name: Exit if no content changes
        if: steps.content_check.outputs.changed == 'false'
        run: |
          echo "No changes detected. Exiting job."
          exit 0

      # 3. source/content/ 폴더를 GitHub Pages 아티팩트로 업로드
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          path: source/content

      # 4. GitHub Pages로 배포
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
